<?php

declare(strict_types=1);

/**
 * First-run setup: detect the web server, write routing config, scaffold the
 * _cms/ directory, and write an editable "Installation successful" homepage.
 *
 * All pure pieces (detection, config text, install-page HTML) are unit-tested;
 * pw_run_setup performs the file writes against the provided directories.
 */

function pw_detect_server(string $software): string
{
    $s = strtolower($software);
    if (str_contains($s, 'nginx')) {
        return 'nginx';
    }
    if (str_contains($s, 'litespeed') || str_contains($s, 'openlitespeed')) {
        return 'litespeed';
    }
    if (str_contains($s, 'apache')) {
        return 'apache';
    }
    return 'unknown';
}

function pw_htaccess_content(): string
{
    return <<<'HTACCESS'
# PageWeave CMS — generated by first-run setup. Safe to remove if you configure
# routing manually. Protects the _cms data dir and routes all other requests to
# the front controller (index.php).
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Never expose the CMS data directory.
    RewriteRule ^_cms/ - [F,L]

    # Serve real files/dirs directly (e.g. /assets/*), route everything else.
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [L]
</IfModule>

# Defense-in-depth: block any .env file (config.env lives in _cms/, already
# denied above, but this catches a misplaced config file in the doc root).
<FilesMatch "\.env$">
    Require all denied
</FilesMatch>

Options -Indexes
HTACCESS;
}

function pw_nginx_content(): string
{
    return <<<'NGINX'
# PageWeave CMS — nginx snippet. Copy this into your server { } block, adjust
# the fastcgi pass to your PHP-FPM socket, then reload nginx.

# Protect the CMS data directory.
location ^~ /_cms/ {
    deny all;
    return 403;
}

# Defense-in-depth: never serve the config file (already covered by the _cms
# deny above, but make the protection explicit).
location ~ /config\.env$ {
    deny all;
    return 403;
}

# Front controller: existing files first, then route to index.php.
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

# PHP handler (adjust path to your PHP-FPM socket).
location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    fastcgi_pass 127.0.0.1:9000;
}
NGINX;
}

function pw_cms_deny_content(): string
{
    return "Require all denied\n";
}

/**
 * Resolve the host shown on the install page. The Host header is fully
 * attacker-controlled, so prefer a configured SITE_URL; otherwise allowlist-
 * validate HTTP_HOST and fall back to 'localhost'. Anything reaching the output
 * is still htmlspecialchars'd, but rejecting obviously-malicious values here
 * avoids persisting garbage (or a poisoned endpoint) into the homepage.
 */
function pw_resolve_host(string $siteUrl, string $httpHost): string
{
    if ($siteUrl !== '') {
        $h = parse_url($siteUrl, PHP_URL_HOST);
        if (is_string($h) && $h !== '') {
            return $h;
        }
    }
    if ($httpHost !== '' && preg_match('/^[A-Za-z0-9._:\[\]-]+$/', $httpHost)) {
        return $httpHost;
    }
    return 'localhost';
}

function pw_install_page_html(string $host, string $mcpPath, bool $mcpEnabled, string $sourceUrl, string $scheme = 'https'): string
{
    $safeHost = htmlspecialchars($host, ENT_QUOTES, 'UTF-8');
    $endpoint = $scheme . '://' . $safeHost . $mcpPath;
    $snippet = json_encode([
        'mcp' => [
            'pageweave-cms' => [
                'type' => 'remote',
                'url' => $scheme . '://' . $host . $mcpPath,
                'headers' => ['Authorization' => 'Bearer YOUR_MCP_KEY'],
            ],
        ],
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);

    $notice = $mcpEnabled
        ? '<p style="color:#16a34a;font-weight:600;">✅ MCP is enabled. Your key is in <code>_cms/config.env</code>.</p>'
        : '<p style="color:#dc2626;font-weight:600;">⚠️ MCP is disabled. Set <code>MCP_KEY</code> in <code>_cms/config.env</code>.</p>';

    return <<<HTML
<div style="max-width:760px;margin:48px auto;font-family:system-ui,Segoe UI,sans-serif;color:#0f172a;line-height:1.6;">
  <h1 style="margin-bottom:0;">✅ Installation successful</h1>
  <p style="color:#475569;">PageWeave CMS is running. Manage this site from your AI coding agent over MCP.</p>

  {$notice}

  <h2>MCP endpoint</h2>
  <p><code>{$endpoint}</code></p>

  <h2>Connect your agent (OpenCode)</h2>
  <p>Add this to your OpenCode config (see <a href="https://opencode.ai/docs/mcp-servers/">the MCP servers docs</a>):</p>
  <pre style="background:#0f172a;color:#e2e8f0;padding:16px;border-radius:8px;overflow:auto;">{$snippet}</pre>

  <h2>Next steps</h2>
  <p>Ask your agent: <em>“Create a homepage for my site.”</em> It will overwrite this page.</p>

  <hr style="margin:32px 0;border:none;border-top:1px solid #e2e8f0;">
  <p style="font-size:0.85rem;color:#64748b;">
    Source: <a href="{$sourceUrl}">{$sourceUrl}</a> &middot;
    PageWeave CMS &middot; AGPL-3.0-or-later
  </p>
</div>
HTML;
}

function pw_is_installed(string $cmsDir): bool
{
    return is_file($cmsDir . '/.installed');
}

/**
 * Generate a fresh 64-hex-char MCP bearer key (32 bytes of entropy).
 */
function pw_generate_mcp_key(): string
{
    return bin2hex(random_bytes(32));
}

/**
 * Run first-time setup. Creates the _cms tree, writes the operator config
 * (_cms/config.env with a generated MCP_KEY — never clobbered), an editable
 * install homepage, the routing config for the detected server, and the
 * .installed marker. Returns what was written plus the active MCP key.
 */
function pw_run_setup(
    string $docRoot,
    string $cmsDir,
    string $serverSoftware,
    string $host,
    string $mcpPath,
    string $scheme = 'https'
): array {
    $defaults = pw_config_defaults();

    @mkdir($cmsDir . '/partials', 0775, true);
    @mkdir($cmsDir . '/pages', 0775, true);
    @mkdir($docRoot, 0775, true);

    // Protect the _cms directory from direct access (Apache/LiteSpeed).
    file_put_contents($cmsDir . '/.htaccess', pw_cms_deny_content(), LOCK_EX);

    // Operator config — create once with a generated key; never overwrite.
    $configEnv = $cmsDir . '/' . PW_CONFIG_FILE;
    if (!is_file($configEnv)) {
        $mcpKey = pw_generate_mcp_key();
        file_put_contents(
            $configEnv,
            pw_config_env_content($mcpKey, $defaults['sourceUrl'], $defaults['siteTitle'], $defaults['siteUrl']),
            LOCK_EX
        );
    } else {
        $existing = pw_load_env_file($configEnv);
        $mcpKey = $existing['MCP_KEY'] ?? '';
    }

    // Editable install homepage — only if none exists yet. A key was just
    // generated (or already present), so MCP is enabled.
    $indexFile = $cmsDir . '/pages/index.html';
    if (!is_file($indexFile)) {
        file_put_contents(
            $indexFile,
            pw_install_page_html($host, $mcpPath, $mcpKey !== '', $defaults['sourceUrl'], $scheme),
            LOCK_EX
        );
    }

    $server = pw_detect_server($serverSoftware);
    $wroteHtaccess = false;
    $wroteNginx = false;

    if ($server === 'apache' || $server === 'litespeed' || $server === 'unknown') {
        $wroteHtaccess = file_put_contents($docRoot . '/.htaccess', pw_htaccess_content(), LOCK_EX) !== false;
    }
    if ($server === 'nginx' || $server === 'unknown') {
        $wroteNginx = file_put_contents($docRoot . '/nginx.conf', pw_nginx_content(), LOCK_EX) !== false;
    }

    file_put_contents($cmsDir . '/.installed', date('c'), LOCK_EX);

    return [
        'server' => $server,
        'wroteHtaccess' => $wroteHtaccess,
        'wroteNginx' => $wroteNginx,
        'mcpKey' => $mcpKey,
    ];
}
